S20 140
procesoseficientes/sonda-2 pull request #127
Opened 2023-07-26 19:33 UTC by elucas2015337

Cancelar ordenes aun no finalizadas

![image](https://github.com/procesoseficientes/sonda-2/assets/54085071/0d9d5146-c423-4de4-ae17-79f6c7168f40)

2023-07-26 19:37 UTC, fabrv requested changes

2023-07-26 19:37 UTC, fabrv commented on src/pages/Cliente/ClientDetailPage.tsx
> +        <IonFab
No usar dos FABs en una pantalla

2023-07-26 22:27 UTC, Palacios999 approved these changes

2023-07-27 16:39 UTC, fabrv approved these changes

2023-07-27 16:39 UTC, merged